// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Column = { name: string, data_type: string, nullable: boolean, is_primary_key: boolean, is_foreign_key: boolean, default: string | null, unique: boolean, };
