// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelationshipVia } from "./RelationshipVia";

export type Relationship = { 
/**
 * Stable id for the React Flow edge.
 */
id: string, 
/**
 * Child side (the table that holds the foreign key), normalized key.
 */
from_table: string, from_columns: Array<string>, 
/**
 * Parent side (the referenced table), normalized key.
 */
to_table: string, to_columns: Array<string>, on_delete: string | null, on_update: string | null, 
/**
 * How this relationship was derived.
 */
via: RelationshipVia,
/**
 * True when the edge was inferred from naming conventions
 * (`<name>_id` -> `<names>`/`<name>.PK`) rather than declared via
 * `FOREIGN KEY` / `REFERENCES`.
 */
inferred: boolean, };
