// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Indicates how a relationship edge was derived.
 */
export type RelationshipVia = "foreign_key" | "inferred" | "view_dependency";
