// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RelationshipCardinality = "one" | "zero_or_one" | "one_or_many" | "zero_or_many";
