// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Relationship } from "./Relationship";
import type { Table } from "./Table";

/**
 * The full parsed schema: every table plus the foreign-key relationships
 * resolved between them, along with any non-fatal warnings collected while
 * parsing (unparseable statements, foreign keys pointing at unknown tables).
 */
export type SchemaModel = { tables: Array<Table>, relationships: Array<Relationship>, warnings: Array<string>, 
/**
 * Detected dialect label ("generic" / "postgres" / "mysql" / ...).
 */
dialect: string, };
