// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Distinguishes regular tables from views in the schema graph.
 */
export type TableKind = "table" | "view";
