// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";
import type { TableKind } from "./TableKind";

export type Table = { 
/**
 * Normalized key used to resolve FKs and as the React Flow node id.
 * Format: lowercased `schema.table` (or just `table` when unqualified).
 */
id: string, name: string, schema: string | null, columns: Array<Column>, 
/**
 * Unique constraints/indexes declared on the table. Each inner array is
 * the constrained column set in declaration order.
 */
unique_constraints: Array<Array<string>>, 
/**
 * Absolute path of the `.sql` file this table was defined in.
 */
source_file: string, 
/**
 * Whether this entry is a regular table or a view.
 */
kind: TableKind, };
